name: PC Backend Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_SECRET }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "TAG=`date +%Y.%m.%d.%H.%M.%S`" >> $GITHUB_ENV
    - name: Build the Docker image
      working-directory: ./pc-backend
      run: |
        docker build . --file Dockerfile --tag jtb75/pc-backend:$TAG --tag jtb75/pc-backend:latest
    - name: Scan the Docker Image
      working-directory: ./pc-backend
      run: |
        curl -X GET -u ${PCC_USER}:${PCC_SECRET} ${PCC_CONSOLE_URL}/api/v1/util/twistcli > twistcli; chmod a+x twistcli;
        ./twistcli images scan -u $PCC_USER -p $PCC_SECRET --address $PCC_CONSOLE_URL --details jtb75/pc-backend:$TAG
    - name: Push the Docker image
      run: |
        docker push jtb75/pc-backend:$TAG
        docker push jtb75/pc-backend:latest
